---
- name: Add key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
  tags: install

- name: Add repo
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: Install DB dependencies
  apt:
    name: mongodb-org
    state: present
  tags: install

- name: Enable systemd service
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
